version: "3.9"

services:
  api-service:
    image: nestjs-mongodb-neo4j/api-service:dev
    container_name: api-service
    build:
      context: .
      dockerfile: apps/api-service/Dockerfile
    env_file:
      - apps/api-service/.env
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
      - MONGO_DATABASE_URI=mongodb://mongodb:27017/nestjs-mongodb-neo4j
      - REDIS_HOST=cache
      - NEO4J_HOST=neo4j
      - RABBITMQ_URI=amqp://user:password@rabbitmq:5672
    ports:
      # Exposed:container
      - "3000:3000"
    depends_on:
      - mongodb
      - neo4j
      - cache
      - rabbitmq
    # rabbitmq and neo4j takes time to start
    # so we restart the service until they are up
    restart: unless-stopped
    develop:
      watch:
        - path: package.json
          action: rebuild
        - path: pnpm-lock.yaml
          action: rebuild
        - path: nest-cli.json
          action: rebuild

  mongodb:
    image: arm64v8/mongo:6.0.5-jammy
    container_name: mongodb
    platform: linux/arm64/v8
    ports:
      - "27017:27017"
    volumes:
      - "mongodb_data:/data/db"
    environment:
      - MONGO_INITDB_DATABASE=nestjs-mongodb-neo4j

  neo4j:
    image: bitnami/neo4j:5.16.0
    container_name: neo4j
    environment:
      - NEO4J_PASSWORD=password
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"
    volumes:
      - "neo4j_data:/bitnami"

  cache:
    image: docker.io/bitnami/redis:7.2
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      # - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "6379:6379"
    volumes:
      - "cache_data:/bitnami/redis/data"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "4369:4369"
      - "5551:5551"
      - "5552:5552"
      - "5672:5672"
      - "25672:25672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - "rabbitmq_data:/bitnami/rabbitmq/mnesia"

volumes:
  mongodb_data:
  cache_data:
  neo4j_data:
  rabbitmq_data:
