export const AUTH_SERVICE = 'AUTH_SERVICE';

export enum AuthCodes {
  LOGIN_SUCCESS = 'AUTH.LOGIN_SUCCESS',
  TOKEN_REFRESHED = 'AUTH.TOKEN_REFRESHED',
}

export enum AuthErrorCodes {
  WRONG_CREDENTIAL = 'AUTH.WRONG_CREDENTIAL',
  EMAIL_OR_PHONE_REQUIRED = 'AUTH.EMAIL_OR_PHONE_REQUIRED',
  JWT_ERROR = 'AUTH.JWT_ERROR',
  JWT_INVALIDATED = 'AUTH.JWT_INVALIDATED',
}

export enum TokenType {
  ACCESS_TOKEN = 'ACCESS_TOKEN',
  REFRESH_TOKEN = 'REFRESH_TOKEN',
}
