export const NEO4J_UNIT_OF_WORK_FACTORY = 'NEO4J_UNIT_OF_WORK_FACTORY';
export const USER_NEO4J_NODE_MODEL_SERVICE = 'USER_NEO4J_NODE_MODEL_SERVICE';
export const FOLLOW_NEO4J_RELATIONSHIP_MODEL_SERVICE =
  'FOLLOW_NEO4J_RELATIONSHIP_MODEL_SERVICE';
export const MOVIE_NEO4J_NODE_MODEL_SERVICE = 'MOVIE_NEO4J_NODE_MODEL_SERVICE';

export const NEO4J_SERVICE = 'NEO4J_SERVICE';
export const DATE_FORMAT = 'yyyy-MM-dd HH:mm:ss';

export enum NodeNames {
  User = 'User',
}

export enum RelationshipTypes {
  Follows = 'FOLLOWS',
}
