export const API_DB_CONNECTION = 'API_DB_CONNECTION';
export const USER_MODEL = 'USER_MODEL';
export const PRIORITY_MODEL = 'PRIORITY_MODEL';
export const CONTACT_MODEL = 'CONTACT_MODEL';
export const FIFTEEN_PLANNER_MODEL = 'FIFTEEN_PLANNER_MODEL';
export const MONGOOSE_UNIT_OF_WORK_FACTORY = 'MONGOOSE_UNIT_OF_WORK_FACTORY';
