export const FOLLOW_AGGREGATE_FACTORY = 'FOLLOW_AGGREGATE_FACTORY';
export const FOLLOW_WRITE_REPOSITORY = 'FOLLOW_WRITE_REPOSITORY';

export const FOLLOW_SERVICE = 'FOLLOW_SERVICE';

export enum FollowCodes {
  CREATED = 'FOLLOW.CREATED',
}

export enum FollowErrorCodes {
  ALREADY_FOLLOWED = 'FOLLOW.ALREADY_FOLLOWED',
}
