name: Docker Build
on:
  pull_request:
    branches:
      - development

jobs:
  build:
    name: 'Build image: ${{ matrix.service }}'
    strategy:
      matrix:
        service: ['api-service']
    runs-on: ubuntu-latest
    env:
      HUSKY: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: benjlevesque/short-sha@v3.0
        id: short-sha
        with:
          length: 6

      - name: Build docker image
        env:
          REPOSITORY: ${{ github.repository }}/${{ matrix.service }}
          TAG: dev-${{ steps.short-sha.outputs.sha }}
        run: |
          docker build \
          -f apps/${{ matrix.service }}/Dockerfile . \
          -t ${{ env.REPOSITORY }}:${{ env.TAG }}

      - name: Docker Images
        run: docker images
